services:
  redis:
    image: redis:latest
    container_name: graysky-redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
      - ./redis-config/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  app:
    build: .
    container_name: graysky-push-notifs
    ports:
      - "3000:3000"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
