# fly.toml app configuration file generated for graysky on 2024-02-02T01:06:41Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#
app = 'graysky'
primary_region = 'lhr'

[build]

[env]
PORT = '8080'

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = false
auto_start_machines = true
min_machines_running = 1
max_machines_running = 1
processes = ['app']

[[vm]]
cpu_kind = 'shared'
cpus = 1
memory_mb = 1024
